---
title: "energy"
author: "Hannah Barrow"
date: "2026-02-10"
output: html_document
---

## Renewable Evergy dataset

```{r}
library(readr)
energy <- read.csv("../../data/IRENA data.csv", skip = 1)
```

## Gapminder dataset

```{r}
library(gapminder)
library(dplyr)
data(gapminder)
gapminder %>% head
```

## Carbon emission

```{r}
library(readr)
library(dplyr)

url <- 'https://nyc3.digitaloceanspaces.com/owid-public/data/co2/owid-co2-data.csv'

carbon <- read_csv(url)
carbon %>% head
```

## Levelized cost of energy

```{r}
library(readr)
library(dplyr)

url <- 'https://raw.githubusercontent.com/ericmkeen/sewanee_esus/master/02_energy_sector/levelized-cost-of-energy.csv'

econ <- read_csv(url)
econ %>% head
```

```{r}
library(ggplot2)
ggplot(econ,
       aes(x = year,
           y = cost,
           color = source))+
  geom_point()+
  geom_hline(yintercept = 0.18, lty = 2)+
  geom_hline(yintercept = 0.05, lty = 2)+
  annotate(geom = "text",
           x = 1988,
           y = 0.1,
           size = 3.5,
           label = "Range of Fossil\nFuel costs")
```

```{r}
library(knitr)

econ %>% 
  filter(year == 2020) %>% 
  group_by(source) %>% 
  summarize(cost = mean(cost, na.rm = TRUE)) %>% 
  kable
```
